### ISSUE TITLE
Ver detalles de un ordenador no funciona

### ISSUE THREAD

**Issue by Bernard2806** [EEST1Chivilcoy/SGE#11]
**Descripción:**
Al intentar acceder a la función de "Ver detalles" de un ordenador, no se muestra la información esperada. El botón parece no responder o el modal de detalles no se carga correctamente.

**Pasos para reproducir:**
1. Ir a la lista de ordenadores en la aplicación.
2. Hacer clic en el botón "Ver detalles" de un ordenador.
3. Observar que la información del ordenador no se muestra.

**Comportamiento esperado:**
Al hacer clic en "Ver detalles", debería abrirse un modal o una página que muestre toda la información relacionada con el ordenador seleccionado.

**Comportamiento actual:**
El botón "Ver detalles" no responde o no muestra ninguna información del ordenador.

**Información adicional:**
- Navegador: Microsoft Edge
     - Versión 130.0.2849.68 (Compilación oficial) (64 bits)

![image](https://github.com/user-attachments/assets/6183bac2-3928-48d2-b249-4e80e8166b98)

**Comment by IgnGom06** [comment]
Este issue se solucionó en el commit anteriormente mencionado 2bd7fbc
