### ISSUE TITLE
Implementar un ABM (Alta, Baja, Modificación) de Salones (Áreas)

### ISSUE THREAD

**Issue by Bernard2806** [EEST1Chivilcoy/SGE#8]
**Descripción:**  
Desarrollar un sistema de Alta, Baja y Modificación (ABM) de Salones para la escuela, con vistas en formato de cartas para facilitar la visualización y asignación de categorías. Este sistema permitirá a los directivos gestionar de forma centralizada los salones, asignándoles categorías que son creadas por los mismos usuarios autorizados.

**Requerimientos:**  
1. **Funcionalidades Básicas del ABM:**
   - Crear, editar y eliminar salones.
   - Asignar una categoría a cada salón. Las categorías pueden ser creadas y administradas por los usuarios autorizados (solo directivos).
   - Distinguir entre dos tipos de salones: Área de uso común y Área privada.

2. **Vista en Cartas:**
   - Implementar una vista en cartas para cada salón que muestre:
     - Imagen representativa del salón.
     - Nombre y categoría asignada.
     - Identificación del tipo de área (común o privada).

3. **Gestión de Categorías:**
   - Crear una sección en la que los directivos puedan agregar, editar y eliminar categorías de salones.
   - Las categorías deben poder asignarse a múltiples salones.

4. **Roles y Permisos:**
   - Restringir el acceso al ABM únicamente a los usuarios con rol de directivo.

5. **Escalabilidad (Implementación Futura):**
   - Preparar la estructura del sistema para la futura implementación de un módulo de reportes de problemas en los salones.

**Criterios de Aceptación:**  
- El ABM permite la creación, edición y eliminación de salones con asignación de imágenes.
- Los directivos pueden asignar y modificar categorías en cada salón.
- Las categorías creadas por el usuario pueden visualizarse y gestionarse en una vista de administración.
- Los salones se muestran en una vista de cartas que facilita su identificación.
- Los roles se gestionan adecuadamente, permitiendo el acceso al ABM solo a usuarios directivos.

**Notas Adicionales:**
- Asegurarse de que el diseño de la interfaz sea intuitivo y permita a los directivos una experiencia fácil al asignar y visualizar salones y sus categorías.
- Considerar el uso de componentes reutilizables para facilitar futuras expansiones del sistema.

**Comment by Bernard2806** [comment]
Ya se estuvo trabajando en este issue en los siguientes commits (ordenados del más reciente al más antiguo):

- d80e723565588680e174e5122f5d2739acc24000
- 5dd7e4f28b3e6f374f039edd927643b09fab4fc9
- ac155d727d839d8e2c9e19c352b41c97f7998c0f

**Comment by IgnGom06** [comment]
Implementación del ABM finalizada en el commit c4ee8ec
