### ISSUE TITLE
Modificación del Modelo de Computadoras: Cambiar el Tipo de Propiedad salon a la Clase Area

### ISSUE THREAD

**Issue by Bernard2806** [EEST1Chivilcoy/SGE#9]
**Descripción:**
Necesitamos modificar el modelo de `Computadoras` para mejorar su estructura. Actualmente, la propiedad `salon` está definida como una cadena de texto (string). Para mejorar la integridad de los datos y facilitar mejores relaciones, proponemos cambiar el tipo de la propiedad `salon` de una cadena a la clase `Area`.

**Cambios Requeridos:**
1. Actualizar la propiedad `salon` en el modelo de `Computadoras` para que haga referencia a la clase `Area`.
2. Asegurarse de que toda la funcionalidad relacionada (por ejemplo, migraciones de base de datos, serializadores y validaciones) se actualice en consecuencia para reflejar este cambio.

**Razón del Cambio:**
- Usar la clase `Area` para la propiedad `salon` proporcionará una representación de datos más estructurada y significativa, lo que permitirá una mejor integración con otros componentes de la aplicación.

**Criterios de Aceptación:**
- La propiedad `salon` debe ser una instancia de la clase `Area`.
- La funcionalidad existente debe permanecer sin cambios, con pruebas adecuadas que confirmen que el cambio no rompe características existentes.

**Impacto:**
Este cambio puede requerir actualizaciones en cualquier código que interactúe con el modelo de `Computadoras`, especialmente donde se utiliza la propiedad `salon`.

**Próximos Pasos:**
- Revisar e implementar los cambios.
- Ejecutar pruebas para asegurar compatibilidad y funcionalidad.

**Comment by IgnGom06** [comment]
Finalizada la modificación del modelo en el commit anteriormente mencionado 75cf29f
